// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rental.db;

#nullable disable

namespace Rental.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260402093436_AddStorageDifferentiation")]
    partial class AddStorageDifferentiation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rental.models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("Rental.models.Storage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MonthlyCosts")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TypeId");

                    b.ToTable("Storages", (string)null);
                });

            modelBuilder.Entity("Rental.models.StorageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MonthlyCosts")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("StorageTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 5,
                            Category = "Garage",
                            MonthlyCosts = 1000m,
                            Name = "Small Garage",
                            Price = 10000m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 15,
                            Category = "Garage",
                            MonthlyCosts = 3000m,
                            Name = "Large Garage",
                            Price = 30000m
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 10,
                            Category = "Garage",
                            MonthlyCosts = 2000m,
                            Name = "Medium Garage",
                            Price = 200000m
                        });
                });

            modelBuilder.Entity("Rental.models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("uuid");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StorageId");

                    b.HasIndex("TypeId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("Rental.models.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("RequiredStorageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Car",
                            Level = "Economy",
                            MonthlyIncome = 500m,
                            Name = "Economy Car",
                            Price = 5000m,
                            RequiredStorageType = "Garage"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Car",
                            Level = "Comfort",
                            MonthlyIncome = 1000m,
                            Name = "Comfort Car",
                            Price = 10000m,
                            RequiredStorageType = "Garage"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Car",
                            Level = "Business",
                            MonthlyIncome = 3000m,
                            Name = "Business Car",
                            Price = 20000m,
                            RequiredStorageType = "Garage"
                        });
                });

            modelBuilder.Entity("Rental.models.Storage", b =>
                {
                    b.HasOne("Rental.models.Company", "Company")
                        .WithMany("Storages")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rental.models.StorageType", "StorageType")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("StorageType");
                });

            modelBuilder.Entity("Rental.models.Vehicle", b =>
                {
                    b.HasOne("Rental.models.Company", "Company")
                        .WithMany("Vehicles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rental.models.Storage", "Storage")
                        .WithMany("Vehicles")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rental.models.VehicleType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Storage");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Rental.models.Company", b =>
                {
                    b.Navigation("Storages");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Rental.models.Storage", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
